#########################
# project configuration #
#########################

cache:
  apt: true
  directories:
    - $HOME/deps

# C++ project
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - libpython3-dev
    - libtbb-dev
env:
  - MINICONDA_PYTHON_VERSION=3.6
  - MINICONDA_PYTHON_VERSION=3.7
compiler:
  - gcc
  - clang

install:
  # create deps dir if not existing
  - DEPS_DIR=${HOME}/deps
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - python3-config --cflags --ldflags
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test_env python=${MINICONDA_PYTHON_VERSION}
  - conda activate test_env
  - export PYTHON_EXECUTABLE=${HOME}/miniconda/bin/python
  - |
    CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cd -

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - find -type f -name '*.py' -exec ${PYTHON_EXECUTABLE} -m py_compile {} +;
  - (mkdir rts/build_MC && cd rts/build_MC && cmake .. -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} -DGAME_DIR=../game_MC && make)
#  - (mkdir rts/build_CF && cd rts/build_CF && cmake .. -DPYTHON_EXECUTABLE=/opt/pyenv/shims/python -DGAME_DIR=../game_CF && make)
#  - (mkdir rts/build_TD && cd rts/build_TD && cmake .. -DPYTHON_EXECUTABLE=/opt/pyenv/shims/python -DGAME_DIR=../game_TD && make)